### ISSUE TITLE
scripts for running dataset 

### ISSUE THREAD

**Issue by kolincc** [chenzRG/Fredformer#1]
Could you provide scripts for running dataset other than the weather dataset, please?

**Comment by xihaopark** [comment]
I appreciate your interest in our project. The scripts for running datasets other than the weather dataset are now available in the scripts/Fedformer/ directory.

**Comment by Respectzz** [comment]
May I ask what environment and script you are using? I cannot reproduce the effect in the paper using FEDformer's script
