### ISSUE TITLE
The second chapter of the thesis

### ISSUE THREAD

**Issue by TiAmo888** [chenzRG/Fredformer#6]
I would like to ask you about the details of Figure 2 in your paper and the part covered in chapter 2. I would like to repeat that this part of the work is not successful.

**Comment by xihaopark** [comment]
Thank you very much for your interest in our work! Did you use a Transformer encoder + linear layer decoder architecture? This architecture has become popular in time series forecasting recently. We used it in our analysis in Chapter 2. In our paper, we trained on single-channel data, where each token represents a timestamp. If your results are not significant, we recommend adjusting the synthetic data, such as increasing the amplitude differences.

**Comment by TiAmo888** [comment]
I tried to see if other networks were transformed in this way, but without success. Did not use the architecture you proposed. Could you give us more details if convenient

**Comment by xihaopark** [comment]
When you mention 'other networks,' are you referring to Transformer-based models or other architectures? As far as I know, MLP architectures also exhibit similar tendencies in practice, which you might want to analyze. I can upload the dataset and code we used in our experiments to this GitHub repository in the future, so please stay tuned. Specifically, we made modifications based on the PatchTST code, setting each token as a timestamp. We also conducted similar observation experiments on other Transformer-based models, and the results have already been presented in the paper.

**Comment by xihaopark** [comment]
Additionally, I'd like to point out that many works use the early stopping technique, where the model stops updating parameters when the accuracy of the validation dataset does not improve. This can prevent us from correctly analyzing the model's training process. If you want to analyze the training process of the model, I recommend not using the early stopping technique.

**Comment by TiAmo888** [comment]
Thank you for your reply and suggestions, looking forward to your future upload of the code
